version: '3.10'

services:
  webapp:
    build:
      context: ./web-app
    ports:
      - "5001:5001"
    environment:
      - .env
    depends_on:
      - mongo
      - machine_learning_client
    command: ["pipenv", "run", "python", "app.py"] 

  machine_learning_client:
    build:
      context: ./machine_learning_client
    environment:
      - .env
    depends_on:
      - mongo
    command: ["pipenv", "run", "python", "ml_client.py"]  

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - .env

volumes:
  mongo_data:
