# .github/workflows/ci.yml
name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black pylint pytest pytest-cov

      # Lint the code with pylint
      - name: Lint code with pylint
        run: |
          pylint ml_client.py

      # Check code formatting with Black
      - name: Check code formatting with Black
        run: |
          black --check ml_client.py

      # Run tests with pytest and generate coverage report
      - name: Run tests with pytest and coverage
        run: |
          pytest --cov=ml_client test_ml_client.py

      # Upload test coverage report
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/
