name: CI

on:
  pull_request:
    branches: [main]

  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies with pipenv
        run: |
          pipenv install --deploy --ignore-pipfile

      - name: Check for required files
        run: |
          if [ ! -f "face_model.h5" ]; then
            echo "Model file not found!"; exit 1;
          fi

      - name: Lint with pylint
        run: |
          pipenv run pylint machine_learning_client/ml_client.py

      - name: Format with Black
        run: |
          pipenv run black --check ml_client.py

      - name: Run tests with pytest and coverage
        run: |
           pipenv run pytest
